name: Hashnode API Workflow

on:
  push:
    branches:
      - main

jobs:
  curl_with_retry:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Command with Retry
        run: |
          for i in {1..5}; do
            curl -H 'User-Agent: Mozilla/5.0' \
                 -H 'CF-Connecting-IP: x.x.x.x' \
                 -H 'Cookie: _cfuid=your_cf_id;' \
                 -H 'Authorization: Bearer YOUR_API_TOKEN' \
                 https://your_api_endpoint.com && break || sleep 5;
          done
